### ISSUE TITLE
Error Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by stone89son** [heroui-inc/next-app-template#1]
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <path> in <svg>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Component Stack
path
svg
MoonFilledIcon
./components/icons.tsx (112:11)
div
label
ThemeSwitch
./components/theme-switch.tsx (19:11)
ul
eval
./node_modules/@nextui-org/navbar/dist/chunk-PSG7VTZC.mjs (20:11)
header

![abc](https://github.com/nextui-org/next-app-template/assets/6795515/e1209160-cfc9-4359-87df-02e54cf21ecb)

**Comment by nikohann** [comment]
Just change the moon icon to another

**Comment by jrgarciadev** [comment]
Fixed
