### ISSUE TITLE
Theme switch log error?

### ISSUE THREAD

**Issue by isaacdarcilla** [heroui-inc/next-app-template#6]
There's an error when the page is set to light mode:

Warning: Prop `aria-label` did not match. Server: "Switch to light mode" Client: "Switch to dark mode"

![image](https://github.com/nextui-org/next-app-template/assets/22732118/a2d6c29f-9970-438b-8575-56fae31353e4)

**Comment by wingkwong** [comment]
Closing - not able to reproduce in main branch
