### ISSUE TITLE
Fonts not working

### ISSUE THREAD

**Issue by redoxahmii** [heroui-inc/next-app-template#7]
i am fairly new to this so changing the fonts inside fonts.ts is not really changing the fonts for my environment
i have tried to set it directly inside the layout.tsx directly but it still does not work that properly.

**Comment by wingkwong** [comment]
in tailwind.config.js, you need to extend the fontFamily in tailwind.config.js. e.g.

```js
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-geist-mono)"],
      },
    },
  },
```
