### ISSUE TITLE
update to next14

### ISSUE THREAD

**Issue by kevincobain2000** [heroui-inc/next-app-template#8]
Update to Next14

https://github.com/nextui-org/next-app-template/blob/28c4c69df3d6af9e71bc1817418338c1d065530b/package.json#L33C23-L33C23

**Comment by MarwanBz** [comment]
Hey @jrgarciadev, I'd like to work on this issue so could you please assign it to me? 
also, I think some people prefer to use the old pages dir in nextJS so what do you think should a create a new repo for the nextjs14 with tailwindCss update? 
thanks,

**Comment by wingkwong** [comment]
Closing - no longer applicable.
