### ISSUE TITLE
Navbar issue

### ISSUE THREAD

**Issue by rogueturnip** [heroui-inc/next-app-template#9]
Thanks for the great starting template.  I'm running into a strange issue.  I've pretty much matched line by line the setup and the navbar is functioning oddly for me.
![image](https://github.com/nextui-org/next-app-template/assets/7782364/0f0bf2b1-6a8b-404a-9d9e-9a31ad11de50)

I don't get the menu icon and when I tap I see the Open/close text toggle but it's not opening the menu.

Any thoughts?

**Comment by isaacdarcilla** [comment]
Do you have updates on this? If fixed, how did you fixed this?

**Comment by realejeh** [comment]
same issue here...

**Comment by isaacdarcilla** [comment]
> same issue here...

@DevIsraelHub You might want to use `pnpm` to install this. It worked for me.

**Comment by realejeh** [comment]
@isaacdarcilla thanks 👍

**Comment by wingkwong** [comment]
Closing - not able to reproduce
